from enum import Enum


class AffordabilityReasonCode(Enum):
    DTI_ABOVE_MAXIMUM = "DTI_ABOVE_MAXIMUM"
    DISPOSABLE_INCOME_BELOW_MINIMUM = "DISPOSABLE_INCOME_BELOW_MINIMUM"
    REPAYMENT_BURDEN_ABOVE_MAXIMUM = "REPAYMENT_BURDEN_ABOVE_MAXIMUM"
    PASSED = "PASSED"